---
title: "Area"
---

> Layers are declared with the [`DRAW` clause](../clause/draw.qmd). Read the documentation for this clause for a thorough description of how to use it.

The area layer is used to display absolute amounts over a sorted x-axis. It can be seen as a [ribbon layer](ribbon.qmd) where the `ymin` is anchored at zero.

## Aesthetics
The following aesthetics are recognised by the area layer.

### Required
* `x`: Position along the x-axis.
* `y`: Position along the y-axis.

### Optional
* `stroke`: The colour of the contour lines.
* `fill`: The colour of the inner area.
* `colour`: Shorthand for setting `stroke` and `fill` simultaneously.
* `opacity`: The opacity of the colours.
* `linewidth`: The width of the contour lines.

## Settings
* `stacking`: Determines how multiple groups are displayed. One of the following:
    * `'off'`: The groups `y`-values are displayed as-is (default).
    * `'on'`: The `y`-values are stacked per `x` position, accumulating over groups.
    * `'fill'`: Like `'on'` but displayed as a fraction of the total per `x` position.

## Data transformation
The area layer does not transform its data but passes it through unchanged.

## Examples

Create a typical area chart

```{ggsql}
VISUALISE FROM ggsql:airquality
DRAW area 
  MAPPING Date AS x, Wind AS y
```

We can reshape the data to 'long format' from our wide format.

```{ggsql}
CREATE TABLE long_airquality AS
SELECT * FROM ggsql:airquality
UNPIVOT(
  Value FOR Series IN (Temp, Wind)
) AS u;
```

Which means we can display multiple series at once, by mapping the identifier to an aesthetic.

```{ggsql}
VISUALISE Date AS x, Value AS y FROM long_airquality
  DRAW area MAPPING Series AS colour
```

We can stack the series by using `stacking => 'on'`. The line serves as a reference for 'unstacked' data.

```{ggsql}
VISUALISE Date AS x, Value AS y, Series AS colour FROM long_airquality
  DRAW area SETTING stacking => 'on', opacity => 0.5
  DRAW line
```

When `stacking => 'fill'` we're plotting stacked proportions. These only make sense if every series is measured in the same absolute unit. (Wind and temperature have different units and the temperature is not absolute.)

```{ggsql}
VISUALISE Date AS x, Value AS y, Series AS colour FROM long_airquality
  DRAW area SETTING stacking => 'fill'
```