---
title: "Ribbon"
---

> Layers are declared with the [`DRAW` clause](../../clause/draw.qmd). Read the documentation for this clause for a thorough description of how to use it.

The ribbon layer is used to display extrema over a sorted x-axis. It can be seen as an [area chart](area.qmd) that is unanchored from zero.

## Aesthetics
The following aesthetics are recognised by the ribbon layer.

### Required
* Primary axis (e.g. `x`): Position along the primary (domain) axis
* Secondary axis min (e.g. `ymin`): Lower position along the secondary (value) axis.
* Secondary axis max (e.g. `ymax`): Upper position along the secondary (value) axis.

### Optional
* `stroke`: The colour of the contour lines.
* `fill`: The colour of the inner area.
* `colour`: Shorthand for setting `stroke` and `fill` simultaneously.
* `opacity`: The opacity of the colours.
* `linewidth`: The width of the contour lines.

## Settings
* `position`: Determines the position adjustment to use for the layer (default is `'identity'`)

## Data transformation
The ribbon layer does not transform its data but passes it through unchanged.

## Orientation
The ribbon has its domain axis as the primary axis and the value range on the secondary axis. The orientation can be deduced from the mapping. To create a horizontal ribbon, map the domain to `y` and use `xmin`/`xmax` for the value range (assuming a default Cartesian coordinate system).

## Examples

A ribbon plot with arbitrary values as minima/maxima

```{ggsql}
VISUALISE FROM ggsql:airquality
  DRAW ribbon
    MAPPING Date AS x, Wind AS ymin, Temp AS ymax
```

Ribbon plots are great for showing the range of some aggregation.

```{ggsql}
// Weekly aggregation of temperature
SELECT 
  WEEKOFYEAR(Date) AS Week, 
  MAX(Temp) AS MaxTemp, 
  MEAN(Temp) AS MeanTemp,
  MIN(Temp) AS MinTemp 
FROM ggsql:airquality
GROUP BY WEEKOFYEAR(Date)

VISUALISE Week AS x
  DRAW ribbon 
    MAPPING MinTemp AS ymin, MaxTemp AS ymax
    SETTING opacity => 0.5
  DRAW line
    MAPPING MeanTemp AS y
```
