---
title: "Rule"
---

> Layers are declared with the [`DRAW` clause](../../clause/draw.qmd). Read the documentation for this clause for a thorough description of how to use it.

The rule layer is used to draw reference lines perpendicular to an axis at specified values. This is useful for adding thresholds, means, medians, event markers, cutoff dates or other guides to the plot. The lines span the full width or height of the panels.
Additionally, the rule layer is used to draw diagonal reference lines based on a coefficient (slope) and intercept. This is useful for adding regression lines, diagonal guides, or mathematical functions to plots.

The parameters are named for the following formula:

$$
y = a + \beta x
$$

Where $a$ is the `intercept` and $\beta$ is the `slope`.

> The rule layer doesn't have a natural extent along the secondary axis. The secondary scale range can thus not be deduced from rule layers. If the rule layer is the only layer in the visualisation, you must specify the position scale range manually.

## Aesthetics
The following aesthetics are recognised by the rule layer.

### Required
* Primary axis (e.g. `x` or `y`): Position along the primary axis.
* `slope`
* `intercept`

Note: you should use either the primary axis, or `slope` together with `intercept`, not both.

### Optional
* `colour`/`stroke`: The colour of the line
* `opacity`: The opacity of the line
* `linewidth`: The width of the line
* `linetype`: The type of the line, i.e. the dashing pattern

## Settings
* `orientation`: The orientation of the layer, see the [Orientation section](#orientation). One of the following: 
    * `'aligned'` to align the layer's primary axis with the coordinate system's first axis.
    * `'transposed'` to align the layer's primary axis with the coordinate system's second axis.

## Data transformation
The rule layer does not transform its data but passes it through unchanged.

## Orientation
Rules are drawn perpendicular to their primary axis. The orientation is deduced directly from the mapping. To create a horizontal rule you map the values to `y` instead of `x` (assuming a default Cartesian coordinate system).
If rule layers use the `slope`/`intercept` formulation, the predictor ($x$) for their primary axis and the response $y$ for its secondary axis. Since the primary axis cannot be deduced from the mapping it must be specified using the `orientation` setting. E.g. to create a vertical linear plot, you need to set `orientation => 'transposed'` to indicate that the primary layer axis follows the second axis of the coordinate system.

## Examples

Add a horizontal threshold line to a time series plot:

```{ggsql}
SELECT Date AS date, temp AS temperature
FROM ggsql:airquality
WHERE Month = 5

VISUALISE 
  DRAW line MAPPING date AS x, temperature AS y
  PLACE rule SETTING y => 70
```

Add a vertical line to mark a specific value:

```{ggsql}
VISUALISE FROM ggsql:penguins
  DRAW point MAPPING bill_len AS x, bill_dep AS y
  PLACE rule SETTING x => 45
```

Add multiple threshold lines with different colors. Note that because we're mapping data from data, we use the `DRAW` clause instead of the `PLACE` clause.

```{ggsql}
WITH thresholds AS (
    SELECT * FROM (VALUES
        (70, 'Target'),
        (80, 'Warning'),
        (90, 'Critical')
    ) AS t(value, label)
)
SELECT Date AS date, temp AS temperature
FROM ggsql:airquality
WHERE Month = 5

VISUALISE 
  DRAW line MAPPING date AS x, temperature AS y
  DRAW rule MAPPING value AS y, label AS colour FROM thresholds
```

Add a diagnoal reference line to a scatterplot. Note we use `slope` and `intercept` instead of `x` or `y`.

```{ggsql}
VISUALISE FROM ggsql:penguins
  DRAW point MAPPING bill_len AS x, bill_dep AS y
  PLACE rule SETTING slope => 0.4, intercept => -1
```

Add multiple reference lines with different colors from a separate dataset. Note we're mapping from data here, so we use `DRAW` instead of `PLACE`.

```{ggsql}
WITH lines AS (
    SELECT * FROM (VALUES
        (0.4, -1, 'Line A'),
        (0.2, 8, 'Line B'),
        (0.8, -19, 'Line C')
    ) AS t(slope, intercept, label)
)
VISUALISE FROM ggsql:penguins
  DRAW point MAPPING bill_len AS x, bill_dep AS y
  DRAW rule
    MAPPING 
      slope AS slope, 
      intercept AS intercept, 
      label AS colour
    FROM lines
```