---
title: Cartesian
---

The cartesian coordinate system is the most well-known and the default for ggsql. It maps the primary positional aesthetic along a horizontal axis and the secondary along a perpendicular vertical axis.

## Default aesthetics
The cartesian coordinate system has the following default positional aesthetics which will be used if no others have been provided:

* **Primary**: `x`
* **Secondary**: `y`

Users can provide their own aesthetic names if needed, e.g.

```ggsql
PROJECT p, q TO cartesian
```

## Settings
* `clip`: Should data be removed if it appears outside the bounds of the coordinate system. Defaults to `true`
* `ratio`: The aspect ratio between the steps on the vertical and horizontal axis. Defaults to `null` (no enforced aspect ratio)

## Examples

### Use custom positional aesthetic names

```{ggsql}
VISUALISE bill_len AS p, bill_dep AS q FROM ggsql:penguins
DRAW point
PROJECT p, q TO cartesian
```

### Flip the x and y axes

```{ggsql}
VISUALISE bill_len AS x, bill_dep AS y FROM ggsql:penguins
DRAW point
PROJECT y, x TO cartesian
```

