---
title: Opacity
---

The `opacity` aesthetic governs the transparency of objects. Depending on the layer it controls the translucency of the fill *or* stroke (if a layer has a natural fill then that is what receives the opacity). Opacity goes from 0 (fully transparent) to 1 (fully opaque). 

Color values (fill or stroke aesthetics) may contain opacity information embedded, e.g. by using hex values with an alpha channel. How such colors are merged with the opacity aesthetic is writer-dependent but the values *should* stack. However, mixing the two is never a good idea in any case.

## Literal values
Opacity is unit less and goes from 0 (fully transparent) to 1 (fully opaque). You can e.g. set the opacity of points to a low value two combat overplotting like so:

```ggsql
DRAW point
    SETTING opacity => 0.2
```

## Palettes
Opacity can only be used for sequential data and has no named palettes. The default for continuous, binned, and ordinal scales is to use the range from 0.1 to 1 and interpolate between them. This can be overwritten by providing a manual output range specification

```ggsql
SCALE opacity TO [0.5, 1]
```
